# Generated by Django 3.2 on 2021-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
