# Generated by Django 3.2 on 2021-05-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Second_app', '0003_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
